### ISSUE TITLE
In Team Member widget, email address not getting picked up

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#21]
See screenshot - the email address is entered into the widget, but clicking on the icon at the published front end doesn't start an email app and the mailto: is empty.
![email](https://cloud.githubusercontent.com/assets/15867551/21041775/95238c9a-bded-11e6-830e-c12e680169a4.jpg)

**Comment by grumpycatsaysno** [comment]
@michehrlich : yes, I confirm this is a bug! Fixing on the way

**Comment by grumpycatsaysno** [comment]
Fixed with latest deployment

**Comment by michehrlich** [comment]
Still not working for me

**Comment by grumpycatsaysno** [comment]
@michehrlich : Can you please open the site in Incognito window? I am afraid there is a caching problem on your side.

**Comment by michehrlich** [comment]
Yes, it is picking up the email address but still not launching the default email app. I think that is because there is a space where there shouldn't be one, namely after the colon in "mailto:" look:
![image](https://cloud.githubusercontent.com/assets/15867551/21154717/ac309d4e-c16f-11e6-852d-ab323f1af5b7.png)

**Comment by michehrlich** [comment]
Fixed, thanks (last sub-issue was default app for email on local machine). Closing
